export default {
  namespaced: true,
  state: {
    categories: [
      {
        id: 1,
        name: "Animals",
        words: [
          "CAT",
          "DOG",
          "HORSE",
          "ELEPHANT",
          "GIRAFFE",
          "LION",
          "TIGER",
          "BEAR",
          "PANDA",
          "KANGAROO",
          "ZEBRA",
          "DEER",
          "WOLF",
          "RABBIT",
          "FROG",
          "MONKEY",
          "SNAKE",
          "PARROT",
          "SHARK",
          "DOLPHIN",
        ],
        image: "/images/game-tile.JPG",
      },
      {
        id: 2,
        name: "Countries",
        words: [
          "JAPAN",
          "CANADA",
          "FRANCE",
          "USA",
          "GERMANY",
          "ITALY",
          "SPAIN",
          "AUSTRALIA",
          "BRAZIL",
          "INDIA",
          "CHINA",
          "MEXICO",
          "ARGENTINA",
          "EGYPT",
          "SOUTH AFRICA",
          "RUSSIA",
          "NORWAY",
          "SWEDEN",
          "FINLAND",
          "SOUTH KOREA",
        ],
        image: "/images/crossword.JPG",
      },
      {
        id: 3,
        name: "Cities",
        words: [
          "LONDON",
          "NEW YORK",
          "TOKYO",
          "PARIS",
          "BERLIN",
          "SYDNEY",
          "ROME",
          "MADRID",
          "BEIJING",
          "MOSCOW",
          "DUBAI",
          "TORONTO",
          "CAPE TOWN",
          "LOS ANGELES",
          "ISTANBUL",
          "SINGAPORE",
          "SAN FRANCISCO",
          "HONG KONG",
          "SEOUL",
          "SAO PAULO",
        ],
        image: "/images/crossword2.JPG",
      },
      {
        id: 4,
        name: "Colors",
        words: [
          "RED",
          "BLUE",
          "GREEN",
          "YELLOW",
          "ORANGE",
          "PURPLE",
          "PINK",
          "BROWN",
          "BLACK",
          "WHITE",
          "GRAY",
          "CYAN",
          "MAGENTA",
          "TEAL",
          "MAROON",
          "INDIGO",
          "VIOLET",
          "OLIVE",
          "BEIGE",
          "TURQUOISE",
        ],
        image: "/images/game2.JPG",
      },
      {
        id: 5,
        name: "Food",
        words: [
          "PIZZA",
          "BURGER",
          "PASTA",
          "SUSHI",
          "TACOS",
          "SALAD",
          "STEAK",
          "FRIES",
          "CHICKEN",
          "FISH",
          "SOUP",
          "ICE CREAM",
          "CAKE",
          "BROWNIE",
          "DONUT",
          "COOKIE",
          "PANCAKE",
          "WAFFLE",
          "OATMEAL",
          "FRUIT",
        ],
        image: "/images/crossword3.JPG",
      },
      {
        id: 6,
        name: "Movies",
        words: [
          "INCEPTION",
          "TITANIC",
          "GLADIATOR",
          "AVATAR",
          "THE MATRIX",
          "JURASSIC PARK",
          "THE GODFATHER",
          "FORREST GUMP",
          "PULP FICTION",
          "THE SHINING",
          "LORD OF THE RINGS",
          "STAR WARS",
          "CASABLANCA",
          "CITIZEN KANE",
          "ET",
          "JAWS",
          "SCHINDLER'S LIST",
          "THE DARK KNIGHT",
          "INCEPTION",
          "MATRIX",
        ],
        image: "/images/crossword4.JPG",
      },
      {
        id: 7,
        name: "Sports",
        words: [
          "FOOTBALL",
          "BASKETBALL",
          "TENNIS",
          "BASEBALL",
          "SOCCER",
          "CRICKET",
          "GOLF",
          "HOCKEY",
          "VOLLEYBALL",
          "RUGBY",
          "SWIMMING",
          "RUNNING",
          "BOXING",
          "MMA",
          "CYCLING",
          "SKIING",
          "SKATEBOARDING",
          "TABLE TENNIS",
          "BADMINTON",
          "DARTS",
        ],
        image: "/images/crossword5.JPG",
      },
      {
        id: 8,
        name: "Music",
        words: [
          "ROCK",
          "JAZZ",
          "CLASSICAL",
          "POP",
          "HIP HOP",
          "R&B",
          "COUNTRY",
          "BLUES",
          "REGGAE",
          "ELECTRONIC",
          "FOLK",
          "SOUL",
          "PUNK",
          "METAL",
          "INDIE",
          "GOSPEL",
          "OPERA",
          "DISCO",
          "LATINO",
          "FUNK",
        ],
        image: "/images/tile2.JPG",
      },
      {
        id: 9,
        name: "Vehicles",
        words: [
          "CAR",
          "BIKE",
          "PLANE",
          "BOAT",
          "TRAIN",
          "TRUCK",
          "SCOOTER",
          "HELICOPTER",
          "SUBMARINE",
          "BUS",
          "VAN",
          "MOTORCYCLE",
          "BICYCLE",
          "TROLLEY",
          "TRACTOR",
          "LIMOUSINE",
          "JET",
          "FERRIS WHEEL",
          "CART",
          "RICKSHAW",
        ],
        image: "/images/word-search.JPG",
      },
    ],
    currentCategory: null,
    gameResults: {
      score: 0,
      time: 0,
    },
  },
  mutations: {
    setCategory(state, category) {
      state.currentCategory = category;
    },
    setGameResults(state, results) {
      state.gameResults = results;
    },
  },
  actions: {
    selectCategory({ commit }, category) {
      commit("setCategory", category);
    },
    setGameResults({ commit }, results) {
      commit("setGameResults", results);
    },
  },
  getters: {
    getCategories(state) {
      return state.categories;
    },
    getCurrentCategory(state) {
      return state.currentCategory;
    },
    getScore(state) {
      return state.gameResults.score;
    },
    getTime(state) {
      return state.gameResults.time;
    },
  },
};
